version: "3"

services:
  hands-on-undo:
    build:
      context: .
    image: hands-on-undo:latest
    environment:
      - LR4J_DIRECTORY=/opt/payara/replay
    volumes:
      - "./replay:/opt/payara/replay"
    ports:
      - "8080:8080"
      - "9001:9001"
